FROM golang:1.25 AS builder
WORKDIR /app
COPY app.go .
RUN CGO_ENABLED=0 go build -o my-server app.go

#Stage 2 
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/my-server .
ENV ENVIRONMENT_NAME=local
EXPOSE 8080
CMD [ "./my-server" ]