name: Docker Env Checker
on: 
    workflow_run:
        workflows: ["Deploy PR Environment"]
        types:
            - completed
jobs:
    test-env:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success'  }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Test Env Var
              working-directory: ./hassani-jr/simple-env-checker/simple-env-checker-env-based-pr-number
              run: |
                sleep 10 
                RESPONSE=$(curl -s httpL//localhost:8080)
                if [[ "RESPONSE" == *"pr-"* ]]; then
                    echo "Environment verified successfully."
                else
                    exit 1
                fi 
